
import com.sun.glass.events.KeyEvent;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author The Survivor
 */
public class JFramePrincipal extends javax.swing.JFrame {

    ColaCircularT cola;
    DefaultTableModel modeloTabla;
    Vector cabeceras = new Vector();

    /**
     * Creates new form JFrame
     */
    public JFramePrincipal() {
        initComponents();
        modeloTabla = (DefaultTableModel) jTableColas.getModel();

        //centrar los encabezados
        ((DefaultTableCellRenderer) jTableColas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

        //centrar los renglones
//        DefaultTableCellRenderer renderA = new DefaultTableCellRenderer();
//        renderA.setHorizontalAlignment(SwingConstants.CENTER);
//        jTableColas.getColumnModel().getColumn(0).setCellRenderer(renderA);
        //evitar que cambie el tamaño
        this.setResizable(false);

        //centrar el JFramePrincipal en la Pantalla
        setLocationRelativeTo(null);

        //asignar titulo superior al JFramePrincipal
        this.setTitle("--Colas Circulares--Demostracion");

        //poner icono a la aplicación
        setIconImage(new ImageIcon(getClass().getResource("/icono.png")).getImage());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_TDatos = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jTF_Dim = new javax.swing.JTextField();
        jButCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFDato = new javax.swing.JTextField();
        jButInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableColas = new javax.swing.JTable();
        jButEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRB_String = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRB_Integer = new javax.swing.JRadioButton();
        jRB_Character = new javax.swing.JRadioButton();
        jTF_DE = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMI_Guardar = new javax.swing.JMenuItem();
        jMI_Abrir = new javax.swing.JMenuItem();
        jMenuInfo = new javax.swing.JMenu();
        jMIVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel2.setText("Ingrese la Dimension de la Cola: ");

        jTF_Dim.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jTF_Dim.setForeground(new java.awt.Color(153, 153, 255));
        jTF_Dim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_Dim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_DimKeyTyped(evt);
            }
        });

        jButCrear.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jButCrear.setText("Crear");
        jButCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCrearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Dato a Insertar: ");

        jTFDato.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jTFDato.setForeground(new java.awt.Color(0, 51, 204));
        jTFDato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDatoKeyTyped(evt);
            }
        });

        jButInsertar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jButInsertar.setText("Insertar");
        jButInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButInsertarActionPerformed(evt);
            }
        });

        jTableColas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableColas);

        jButEliminar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jButEliminar.setText("Eliminar");
        jButEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel4.setText("DATO ELIMINADO");

        BG_TDatos.add(jRB_String);
        jRB_String.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jRB_String.setText("String");
        jRB_String.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_StringActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione el Tipo de Dato a Guardar:  ");

        BG_TDatos.add(jRB_Integer);
        jRB_Integer.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jRB_Integer.setText("Integer");

        BG_TDatos.add(jRB_Character);
        jRB_Character.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jRB_Character.setText("Character");

        jTF_DE.setEditable(false);
        jTF_DE.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jTF_DE.setForeground(new java.awt.Color(204, 0, 0));
        jTF_DE.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jMenuBar1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N

        jMenuFile.setText("Archivo");
        jMenuFile.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N

        jMI_Guardar.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jMI_Guardar.setText("Guardar");
        jMI_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_GuardarActionPerformed(evt);
            }
        });
        jMenuFile.add(jMI_Guardar);

        jMI_Abrir.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jMI_Abrir.setText("Abrir");
        jMI_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_AbrirActionPerformed(evt);
            }
        });
        jMenuFile.add(jMI_Abrir);

        jMenuBar1.add(jMenuFile);

        jMenuInfo.setText("Acerca de...");
        jMenuInfo.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jMenuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInfoActionPerformed(evt);
            }
        });

        jMIVersion.setText("Version App");
        jMIVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIVersionActionPerformed(evt);
            }
        });
        jMenuInfo.add(jMIVersion);

        jMenuBar1.add(jMenuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRB_Integer)
                                .addGap(82, 82, 82)
                                .addComponent(jRB_String)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRB_Character))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTFDato, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButInsertar)
                                    .addGap(60, 60, 60))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButEliminar)
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTF_DE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jLabel2)
                    .addGap(29, 29, 29)
                    .addComponent(jTF_Dim, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(48, 48, 48)
                    .addComponent(jButCrear)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRB_Integer)
                    .addComponent(jRB_String)
                    .addComponent(jRB_Character))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButInsertar)
                    .addComponent(jTFDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTF_DE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTF_Dim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButCrear))
                    .addContainerGap(238, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTF_DimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_DimKeyTyped
        // esto es para que detecte solo numeros en la dimension
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }

        //al presionar enter el boton haga click
        char enter = evt.getKeyChar();
        if (enter == KeyEvent.VK_ENTER) {
            this.jButCrear.doClick();
        }
    }//GEN-LAST:event_jTF_DimKeyTyped

    private void jButCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCrearActionPerformed
        int dimension = Integer.parseInt(this.jTF_Dim.getText());
        cola = new ColaCircularT(dimension);
        modeloTabla.setColumnCount(dimension);

        //inicio headerchange
        //con esto se hace para que cuando el usuario digite la dimension 
        //de la cola, las cabeceras de la tabla autoincrementen
        modeloTabla.setColumnCount(dimension);

        //int cabecera = 0;//inicialmente comienza en cero para simular el vector donde se almacenan los datos de la cola 
        int cabecera = 1;//inicialice en 1 para que el usuario tenga una mejor comprension 
        JTableHeader head = jTableColas.getTableHeader();
        TableColumnModel tcm = head.getColumnModel();
        for (int i = 0; i < jTableColas.getColumnCount(); i++) {
            TableColumn tabCM = tcm.getColumn(i);
            tabCM.setHeaderValue(cabecera++);
        }
        jTableColas.repaint();
//fin headerchange

        //centrar los renglones
        DefaultTableCellRenderer renderA = new DefaultTableCellRenderer();
        renderA.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < dimension; i++) {
            jTableColas.getColumnModel().getColumn(i).setCellRenderer(renderA);
        }


    }//GEN-LAST:event_jButCrearActionPerformed

    private void jButInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButInsertarActionPerformed

        try {
            if (!cola.esta_llena()) {
                if (this.jRB_Integer.isSelected()) {
                    int val = Integer.parseInt(this.jTFDato.getText());
                    cola.insertar(val, modeloTabla);
                    jTFDato.setText("");
                    jTFDato.requestFocus();
                } else if (this.jRB_String.isSelected()) {
                    String val = this.jTFDato.getText();
                    cola.insertar(val, modeloTabla);
                    jTFDato.setText("");
                    jTFDato.requestFocus();
                } else if (this.jRB_Character.isSelected()) {
                    char val = this.jTFDato.getText().charAt(0);
                    cola.insertar(val, modeloTabla);
                    jTFDato.setText("");
                    jTFDato.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null, "COLA LLENA - (Overflow)");
                jTFDato.setText("");
                jTFDato.requestFocus();
            }
        } catch (NumberFormatException e) {
            jTFDato.setText("Error");
            jTFDato.requestFocus();
        }
    }//GEN-LAST:event_jButInsertarActionPerformed

    private void jButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarActionPerformed
        try {
            if (!cola.esta_vacia()) {
                cola.eliminar(modeloTabla, jTF_DE);
            } else {
                JOptionPane.showMessageDialog(null, "COLA VACIA - (Underflow)");
                jTFDato.setText("");
                jTFDato.requestFocus();
                this.jTF_DE.setText("");
            }
        } catch (NumberFormatException e) {
            jTFDato.setText("Error");
            jTFDato.requestFocus();
        }
    }//GEN-LAST:event_jButEliminarActionPerformed

    private void jTFDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDatoKeyTyped
        //al presionar enter el boton haga click
        char enter = evt.getKeyChar();
        if (enter == KeyEvent.VK_ENTER) {
            this.jButInsertar.doClick();
        }
    }//GEN-LAST:event_jTFDatoKeyTyped

    private void jRB_StringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_StringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_StringActionPerformed

    private void jMI_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_GuardarActionPerformed
        try {
            FileWriter fw;
            PrintWriter pw;

            fw = new FileWriter("datos.txt");
            pw = new PrintWriter(fw);
            for (Object dato : cola.datos) {
                pw.print(dato);
            }

            pw.close();
            JOptionPane.showMessageDialog(null, "Datos Guardados");
            //abre el archivo despues de haber almacenado los datos
             Desktop.getDesktop().open(new File("datos.txt"));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Datos NO Guardados");
        }
    }//GEN-LAST:event_jMI_GuardarActionPerformed

    private void jMenuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInfoActionPerformed

    }//GEN-LAST:event_jMenuInfoActionPerformed

    private void jMIVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIVersionActionPerformed
        this.dispose();
        JFrameInfo fi = new JFrameInfo();
        fi.setVisible(true);
    }//GEN-LAST:event_jMIVersionActionPerformed

    private void jMI_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_AbrirActionPerformed
        cola = new ColaCircularT("datos.txt".length());
        jTableColas.setModel(cola.lista());
    }//GEN-LAST:event_jMI_AbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG_TDatos;
    private javax.swing.JButton jButCrear;
    private javax.swing.JButton jButEliminar;
    private javax.swing.JButton jButInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMIVersion;
    private javax.swing.JMenuItem jMI_Abrir;
    private javax.swing.JMenuItem jMI_Guardar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JRadioButton jRB_Character;
    private javax.swing.JRadioButton jRB_Integer;
    private javax.swing.JRadioButton jRB_String;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDato;
    private javax.swing.JTextField jTF_DE;
    private javax.swing.JTextField jTF_Dim;
    private javax.swing.JTable jTableColas;
    // End of variables declaration//GEN-END:variables
}
